# Generated by Django 2.0.6 on 2018-06-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('name_on_card', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('American Express', 'American Express'), ('Mastercard', 'Mastercard'), ('Visa', 'Visa')], default='Mastercard', max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('security_code', models.CharField(max_length=3)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appCardVendor.Card')),
            ],
        ),
    ]
