# Generated by Django 2.0.6 on 2018-06-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCardVendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.BigIntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='security_code',
            field=models.PositiveSmallIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('American Express', 'American Express'), ('Mastercard', 'Mastercard'), ('Visa', 'Visa')], default='American Express', max_length=50),
        ),
    ]
