# Generated by Django 2.0.6 on 2018-06-26 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCardVendor', '0003_auto_20180626_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{1,16}$', message='Card number has to be 16 digits, no spaces')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='security_code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$', message='Security code has to be 3 or 4 digits, no spaces')]),
        ),
    ]
